# 配置项备份文件
server:
  port: 9377

spring:
  application:
    name: dev-service
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1902608505
    hikari:
      #设置事务自动提交
      auto-commit: true
      #设置最大连接数
      maximum-pool-size: 10
      minimum-idle: 10
      #获取连接是，检测语句
      connection-test-query: select 1
      #连接超时时间
      connection-timeout: 20000
      #其它属性
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    username:
    password:
    connect-timeout: 10s
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sdpzhong.dev.entity
  #扫描mapper文件
  #mapper-locations: classpath:mapper/**/*.xml


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）该属性依赖于is-share=true
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # token 前缀
  # token-prefix: Bearer
  # 是否尝试从cookie中获取token
  isReadCookie: false
